data: german-gender
seed: 42
NCF: 100
savedir: Results/German/
modelSF:
  base_score: 0.5
  booster: 'gbtree'
  colsample_bylevel: 1
  colsample_bynode: 1
  colsample_bytree: 0.6
  enable_categorical: False
  eval_metric: 'logloss'
  gamma: 0.1
  gpu_id: -1
  grow_policy: 'depthwise'
  importance_type: None
  interaction_constraints: ''
  learning_rate: 0.1
  max_delta_step: 0
  max_depth: 3
  min_child_weight: 5
  monotone_constraints: '()'
  n_estimators: 50
  n_jobs: 1
  num_parallel_tree: 1
  predictor: 'auto'
  random_state: 42
  reg_alpha: 0.1
  reg_lambda: 1
  scale_pos_weight: 1
  subsample: 1
  tree_method: 'exact'
  use_label_encoder: False
  validate_parameters: 1
models:
  AdvDeb:
    prot_attr: [ 'gender' ]
    adversary_loss_weight: 0.05
    num_epochs: 70
    batch_size: 64
    classifier_num_hidden_units: 128
    random_state: 42
  LR:
    C: 0.03359818286283781
    class_weight: 'balanced'
    solver: 'sag'
    warm_start: True
    random_state: 42
  SVM:
    C: 1
    probability: True
    random_state: 42
  LGB:
    colsample_bytree: 0.6
    device: 'cpu'
    metric: 'binary_logloss'
    n_estimators: 300
    num_leaves: 3
    objective: 'binary'
    reg_lambda: 0.01
    n_jobs: 1
    seed: 42
  XGB:
    base_score: 0.5
    booster: 'gbtree'
    colsample_bylevel: 1
    colsample_bynode: 1
    colsample_bytree: 0.6
    enable_categorical: False
    eval_metric: 'logloss'
    gamma: 0.1
    gpu_id: -1
    importance_type: None
    interaction_constraints: ''
    learning_rate: 0.1
    max_delta_step: 0
    max_depth: 3
    min_child_weight: 5
    monotone_constraints: '()'
    n_estimators: 50
    n_jobs: 1
    num_parallel_tree: 1
    predictor: 'auto'
    random_state: 42
    reg_alpha: 0.1
    reg_lambda: 1
    scale_pos_weight: 1
    subsample: 1
    tree_method: 'exact'
    use_label_encoder: False
    validate_parameters: 1
  LFERM:
    C: 0.01
    kernel: 'linear'
    probability: True
    random_state: 42