data: crime-race
seed: 42
NCF: 100
typeCF: ['genetic', 'KDtree']
savedir: Results/Crime/
modelSF:
  base_score: 0.5
  booster: 'gbtree'
  callbacks: None
  colsample_bylevel: 1
  colsample_bynode: 1
  colsample_bytree: 0.8
  early_stopping_rounds: None
  enable_categorical: False
  eval_metric: 'logloss'
  gamma: 0.01
  gpu_id: -1
  grow_policy: 'depthwise'
  importance_type: None
  interaction_constraints: ''
  learning_rate: 0.1
  max_bin: 256
  max_cat_to_onehot: 4
  max_delta_step: 0
  max_depth: 3
  max_leaves: 0
  min_child_weight: 1
  monotone_constraints: '()'
  n_estimators: 300
  n_jobs: 1
  num_parallel_tree: 1
  predictor: 'auto'
  random_state: 42
  reg_alpha: 0.1
  reg_lambda: 1
models:
  LR:
    C: 0.615848211066026
    class_weight: 'balanced'
    fit_intercept: False
    penalty: 'l1'
    solver: 'liblinear'
    random_state: 42
    tol: 0.00001
  DT:
    ccp_alpha: 0.001
    criterion: 'entropy'
    max_depth: 5
    max_features: 'sqrt'
    min_samples_leaf: 4
    random_state: 42
  RF:
    max_depth: 10
    max_features: 'auto'
    n_estimators: 400
    random_state: 42
  MLP:
    early_stopping: True
    hidden_layer_sizes: (64,)
    learning_rate: 'adaptive'
    max_iter: 120
    random_state: 42
  SVM:
    C: 0.1
    kernel: 'linear'
    class_weight: 'balanced'
    probability: True
    random_state: 42
  LGB:
    colsample_bytree: 0.8
    device: 'cpu'
    learning_rate: 0.05
    metric: 'binary_logloss'
    n_estimators: 300
    num_leaves: 3
    objective: 'binary'
    reg_alpha: 0.05
    reg_lambda: 0.03
    n_jobs: 1
    seed: 42
  XGB:
    base_score: 0.5
    booster: 'gbtree'
    callbacks: None
    colsample_bylevel: 1
    colsample_bynode: 1
    colsample_bytree: 0.8
    early_stopping_rounds: None
    enable_categorical: False
    eval_metric: 'logloss'
    gamma: 0.01
    gpu_id: -1
    grow_policy: 'depthwise'
    importance_type: None
    interaction_constraints: ''
    learning_rate: 0.1
    max_bin: 256
    max_cat_to_onehot: 4
    max_delta_step: 0
    max_depth: 3
    max_leaves: 0
    min_child_weight: 1
    monotone_constraints: '()'
    n_estimators: 50
    n_jobs: 1
    num_parallel_tree: 1
    predictor: 'auto'
    random_state: 42
    reg_alpha: 0.01
    reg_lambda: 1
  AdvDeb:
    prot_attr: ['race']
    adversary_loss_weight: 0.1
    num_epochs: 100
    batch_size: 512
    classifier_num_hidden_units: 64
    random_state: 42
  LFERM:
    C: 0.01
    kernel: 'linear'
    probability: True
    random_state: 42
  FairC:
    sensitive_feature: 'race'
    output: 'ViolentCrimesPerPop'
    setting: 'c'
    c: 0.001
    seed: 42