data: adult-gender
seed: 42
NCF: 1
savedir: Results/Adult-debiased/
modelSF:
  base_score: 0.5
  booster: 'gbtree'
  colsample_bylevel: 1
  colsample_bynode: 1
  colsample_bytree: 0.6
  enable_categorical: False
  eval_metric: 'logloss'
  gamma: 0.01
  gpu_id: -1
  importance_type: None
  interaction_constraints: ''
  learning_rate: 0.001
  max_delta_step: 0
  max_depth: 3
  min_child_weight: 1
  monotone_constraints: '()'
  n_estimators: 50
  n_jobs: 1
  num_parallel_tree: 1
  predictor: 'auto'
  random_state: 42
  reg_alpha: 0.1
  reg_lambda: 1
  scale_pos_weight: 0.4813641988789401
  seed: 42
  subsample: 1.0
  tree_method: 'exact'
  use_label_encoder: False
  validate_parameters: 1
models:
  LR:
    C: 1.623776739188721
    class_weight: 'balanced'
    penalty: 'l1'
    solver: 'liblinear'
    n_jobs: 1
  SVM:
    C: 0.1
    class_weight: 'balanced'
    gamma: 'auto'
    probability: True
    random_state: 42
  LGB:
    colsample_bytree: 0.6
    device: 'cpu'
    max_depth: 5
    metric: 'binary_logloss'
    n_estimators: 300
    num_leaves: 50
    objective: 'binary'
    reg_alpha: 0.01
    reg_lambda: 0.03
    n_jobs: 1
    seed: 42
  XGB:
    base_score: 0.5
    booster: 'gbtree'
    colsample_bylevel: 1
    colsample_bynode: 1
    colsample_bytree: 0.6
    enable_categorical: False
    eval_metric: 'logloss'
    gamma: 0.01
    gpu_id: -1
    importance_type: None
    interaction_constraints: ''
    learning_rate: 0.1
    max_delta_step: 0
    max_depth: 5
    min_child_weight: 1
    monotone_constraints: '()'
    n_estimators: 300
    n_jobs: 1
    num_parallel_tree: 1
    predictor: 'auto'
    random_state: 42
    reg_alpha: 0.01
    reg_lambda: 1
    scale_pos_weight: 1
    seed: 42
    subsample: 0.8
    tree_method: 'exact'
    use_label_encoder: False
    validate_parameters: 1
  AdvDeb:
    prot_attr: ['gender']
    adversary_loss_weight: 0.1
    num_epochs: 50
    batch_size: 256
    classifier_num_hidden_units: 256
    random_state: 42
  LFERM:
    C: 0.01
    kernel: 'linear'
    probability: True
    random_state: 42
