data: adult-gender
seed: 42
NCF: 100
typeCF: ['MACE']
savedir: Results/Adult-debiased/
modelSF:
  base_score: 0.5
  booster: 'gbtree'
  colsample_bylevel: 1
  colsample_bynode: 1
  colsample_bytree: 0.6
  enable_categorical: False
  eval_metric: 'logloss'
  gamma: 0.01
  gpu_id: -1
  importance_type: None
  interaction_constraints: ''
  learning_rate: 0.001
  max_delta_step: 0
  max_depth: 3
  min_child_weight: 1
  monotone_constraints: '()'
  n_estimators: 50
  n_jobs: 1
  num_parallel_tree: 1
  predictor: 'auto'
  random_state: 42
  reg_alpha: 0.1
  reg_lambda: 1
  scale_pos_weight: 0.4813641988789401
  seed: 42
  subsample: 1.0
  tree_method: 'exact'
  use_label_encoder: False
  validate_parameters: 1
models:
  LR:
    C: 1.623776739188721
    class_weight: 'balanced'
    penalty: 'l1'
    solver: 'liblinear'
    n_jobs: 1
  DT:
    ccp_alpha: 0.001
    criterion: 'entropy'
    max_depth: 9
    max_features: 'sqrt'
    min_samples_split: 3
    random_state: 42
  RF:
    max_depth: 20
    max_features: 'auto'
    min_samples_leaf: 4
    min_samples_split: 10
    random_state: 42
  MLP:

